// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIbovY4Jde0cN3HKwoAjBKUtTaIJd9gog',
    appId: '1:823045762127:web:23a679e2ca2c7757e40e3a',
    messagingSenderId: '823045762127',
    projectId: 'tasky-pro-d6f85',
    authDomain: 'tasky-pro-d6f85.firebaseapp.com',
    storageBucket: 'tasky-pro-d6f85.firebasestorage.app',
    measurementId: 'G-ND7SFMRG5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9h93TiXkshN2kXdEhzQ_bq4SHsJ7Cewg',
    appId: '1:823045762127:android:1282c398938cfe3ae40e3a',
    messagingSenderId: '823045762127',
    projectId: 'tasky-pro-d6f85',
    storageBucket: 'tasky-pro-d6f85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoEU1IcSjfg7f4qZIRMngOM4kl96NPSYQ',
    appId: '1:823045762127:ios:b1298f8afa99085be40e3a',
    messagingSenderId: '823045762127',
    projectId: 'tasky-pro-d6f85',
    storageBucket: 'tasky-pro-d6f85.firebasestorage.app',
    iosBundleId: 'com.example.taskyPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoEU1IcSjfg7f4qZIRMngOM4kl96NPSYQ',
    appId: '1:823045762127:ios:b1298f8afa99085be40e3a',
    messagingSenderId: '823045762127',
    projectId: 'tasky-pro-d6f85',
    storageBucket: 'tasky-pro-d6f85.firebasestorage.app',
    iosBundleId: 'com.example.taskyPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIbovY4Jde0cN3HKwoAjBKUtTaIJd9gog',
    appId: '1:823045762127:web:b1d8b9ee7ffe995ee40e3a',
    messagingSenderId: '823045762127',
    projectId: 'tasky-pro-d6f85',
    authDomain: 'tasky-pro-d6f85.firebaseapp.com',
    storageBucket: 'tasky-pro-d6f85.firebasestorage.app',
    measurementId: 'G-LZ9BP6K8W3',
  );
}
